config/routes.rb
Idbrasil::Application.routes.draw do
  
  get "api/get_customers"

  get "api/get_customer"

  get "api/get_products"

  get "api/get_product"

  resources :budgets

  resources :customers

  resources :products
  
  get "errors/404" => "errors#page_not_found"
  get "errors/unauthorized" => "errors#unauthorized"
  
  resources :users
  
  root :to => "home#index"
  
  match "/:action", :controller => "home"
  match "/api/:action", :controller => "api"

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :cost, :description, :forsale, :name, :profit
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html { render :layout => nil }# new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation alert alert-error">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table>
	<tr>
		<td><%= f.label :name %></td>
		<td><%= f.text_field :name %>  </td>
	</tr>
	<tr>
		<td><%= f.label :description %></td>
		<td><%= f.text_area :description , :style => "max-height:100px" %></td>
	</tr>
	<tr>
		<td><%= f.label :cost %></td>
		<td><%= f.text_field :cost %></td>
	</tr>
	<tr>
		<td><%= f.label :profit %></td>
		<td><%= f.text_field :profit %></td>
	</tr>
	<tr>
		<td><%= f.label :forsale %></td>
		<td><%= f.check_box :forsale %></td>	
	</tr>
</table>
  <div class="actions">
    <button type="submit" class="btn btn-success">Save</button>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products</h1>

<table class="table table-bordered table-headed table-hover">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Cost</th>
    <th>Profit</th>
    <th>Forsale</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.description %></td>
    <td><%= product.cost %></td>
    <td><%= product.profit %></td>
    <td><%= product.forsale %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', "#", :class=> "btn", :onclick => "new_product()" %>
<script>
	function new_product()
	{
		$("#new-product").find(".modal-body").html('<%= image_tag 'loading.gif' %>');
		$("#new-product").modal();
		$("#new-product").find(".modal-body").load("/products/new");
	}
</script>
<div id="new-product" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <div class="modal-body">
    	
    </div>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<% if notice %>
<p id="notice alert alert-info"><%= notice %></p>
<% end %>

<legend><%= @product.name %></legend>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Cost:</b>
  <%= @product.cost %>
</p>

<p>
  <b>Profit:</b>
  <%= @product.profit %>
</p>

<p>
  <b>Forsale:</b>
  <%= @product.forsale %>
</p>


<%= link_to 'Edit', edit_product_path(@product), :class => "btn btn-primary" %>
<%= link_to 'Back', products_path, :class=> "btn" %>